language: node_js
node_js:
  - stable
cache: yarn
script:
  - node_modules/.bin/travis-github-status lint jest codeclimate
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d3ef59f99b0a3955be68
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
